name: Build on every push

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@266f5c09359450c39019a6da38f2b331e7122918
  gradle-build:
    uses: walt-id/waltid-identity/.github/workflows/gradle.yml@3c360ff47f15ed48833e75df5fc39c6a22356912
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
  docker-matrix:
    uses: walt-id/waltid-identity/.github/workflows/load-json.yml@927c4233610e90dd8a57418662fad7293b7b29a4
    with:
      jsonpath: ".github/workflows/data/docker-matrix.json"
  docker:
    uses: walt-id/waltid-identity/.github/workflows/docker.yml@3c360ff47f15ed48833e75df5fc39c6a22356912
    secrets: inherit
    needs: [ version, docker-matrix ]
    with:
      images: ${{ needs.docker-matrix.outputs.json }}
      version: ${{ needs.version.outputs.release_version }}
      artifact: true
  api-docker-matrix:
    uses: walt-id/waltid-identity/.github/workflows/load-json.yml@927c4233610e90dd8a57418662fad7293b7b29a4
    with:
      jsonpath: ".github/workflows/data/api-docker-matrix.json"
  api-docker:
    uses: walt-id/waltid-identity/.github/workflows/api-docker.yml@a1fc203a9c3f1f007458db808df1711a2d2e3597
    secrets: inherit
    needs: [ version, api-docker-matrix ]
    with:
      images: ${{ needs.api-docker-matrix.outputs.json }}
      version: ${{ needs.version.outputs.release_version }}
      artifact: true
  ebsi-ct-v3:
    uses: walt-id/waltid-identity/.github/workflows/ebsictv3.yml@834fc56b855b35fe0f71f8a37fe2701f1a8c9150
    needs: [ version, docker, api-docker ]
    secrets: inherit
    with:
      artifact: issuer-api
      tag: "waltid/issuer-api:${{ needs.version.outputs.release_version }}"
  compose-test:
    uses: walt-id/waltid-identity/.github/workflows/docker-compose-testing.yml@30f3806290f5652dd371a682cf17961250607e71
    needs: [ version, docker, api-docker ]
    secrets: inherit
    with:
      artifact: true
      tag: "${{ needs.version.outputs.release_version }}"
