name: Deploy manually to test environment

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Custom version'
        required: false
jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@266f5c09359450c39019a6da38f2b331e7122918
    with:
      preferred: ${{ inputs.release_version }}
  gradle:
    uses: walt-id/waltid-identity/.github/workflows/gradle.yml@cf46ed618f9b296fd9b63c7207ca288855bb5343
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
  docker-matrix:
    uses: walt-id/waltid-identity/.github/workflows/load-json.yml@927c4233610e90dd8a57418662fad7293b7b29a4
    with:
      jsonpath: ".github/workflows/data/docker-matrix.json"
  docker:
    uses: walt-id/waltid-identity/.github/workflows/docker.yml@cf46ed618f9b296fd9b63c7207ca288855bb5343
    secrets: inherit
    needs: [ version, docker-matrix ]
    with:
      images: ${{ needs.docker-matrix.outputs.json }}s
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  enterprise-api-docker:
    uses: walt-id/waltid-identity/.github/workflows/enterprise-api-docker.yml@cf46ed618f9b296fd9b63c7207ca288855bb5343
    secrets: inherit
    needs: [ version, docker-matrix ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  deploy:
    uses: walt-id/waltid-identity/.github/workflows/deployment.yml@48f4fe9ea499a1b6a59c22bff9c57f6af849cee8
    secrets: inherit
    needs: [ version, gradle, docker ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  tag:
    uses: walt-id/waltid-identity/.github/workflows/tag.yml@266f5c09359450c39019a6da38f2b331e7122918
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}